
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
        - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
    depends_on:
      - api
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
  linebot:
    build:
      context: .
      dockerfile: linebot.dockerfile
    depends_on:
      - api

volumes:
  db-data:
