
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
        - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["/app/main"]
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT=${ENDPOINT}
    depends_on:
      - api
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
  linebot:
    build:
      context: .
      dockerfile: linebot.dockerfile
    depends_on:
      - api
    ports:
      - "7000:7000"

volumes:
  db-data:
