
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
        - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file: ".env"
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  linebot:
    build:
      context: .
      dockerfile: linebot.dockerfile
    env_file: ".env"
    depends_on:
      - api

volumes:
  db-data:
