
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
        - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file: ".env"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - /var/log/api:/var/log

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "81:81"
  #     - "50051:50051"
  #   depends_on:
  #     - frontend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - images:/var/images

  # linebot:
  #   build:
  #     context: .
  #     dockerfile: linebot.dockerfile
  #   env_file: ".env"
  #   depends_on:
  #     - api
  #   volumes:
  #     - images:/var/images
  #     - /var/log/linebot:/var/log
  #   ports:
  #     - "7000:7000"
      
volumes:
  db-data:
  images:
