DROP TABLE IF EXISTS "settlements";
DROP TABLE IF EXISTS "expenses";
DROP TABLE IF EXISTS "members";
DROP TABLE IF EXISTS "group_invitations";
DROP TABLE IF EXISTS "groups";
DROP TABLE IF EXISTS "users";