// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at
FROM groups
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
