// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Expense struct {
	ID          int64     `json:"id"`
	GroupID     int64     `json:"group_id"`
	PayerID     string    `json:"payer_id"`
	Amount      int64     `json:"amount"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	IsSettled   bool      `json:"is_settled"`
}

type Group struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupInvitation struct {
	Code      string    `json:"code"`
	GroupID   int64     `json:"group_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupMember struct {
	GroupID   int64     `json:"group_id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Settlement struct {
	GroupID     int64  `json:"group_id"`
	PayerID     string `json:"payer_id"`
	PayeeID     string `json:"payee_id"`
	Amount      int64  `json:"amount"`
	IsConfirmed bool   `json:"is_confirmed"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type UserExpense struct {
	ExpenseID int64  `json:"expense_id"`
	UserID    string `json:"user_id"`
	Share     int64  `json:"share"`
}
