// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settlements.sql

package db

import (
	"context"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (payer_id, payee_id, amount)
VALUES ($1, $2, $3)
RETURNING payer_id, payee_id, amount
`

type CreateSettlementParams struct {
	PayerID int32  `json:"payer_id"`
	PayeeID int32  `json:"payee_id"`
	Amount  string `json:"amount"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, createSettlement, arg.PayerID, arg.PayeeID, arg.Amount)
	var i Settlement
	err := row.Scan(&i.PayerID, &i.PayeeID, &i.Amount)
	return i, err
}

const deleteSettlement = `-- name: DeleteSettlement :exec
DELETE FROM settlements
WHERE payer_id = $1 AND payee_id = $2
`

type DeleteSettlementParams struct {
	PayerID int32 `json:"payer_id"`
	PayeeID int32 `json:"payee_id"`
}

func (q *Queries) DeleteSettlement(ctx context.Context, arg DeleteSettlementParams) error {
	_, err := q.db.ExecContext(ctx, deleteSettlement, arg.PayerID, arg.PayeeID)
	return err
}

const getSettlement = `-- name: GetSettlement :one
SELECT payer_id, payee_id, amount
FROM settlements
WHERE payer_id = $1 AND payee_id = $2
`

type GetSettlementParams struct {
	PayerID int32 `json:"payer_id"`
	PayeeID int32 `json:"payee_id"`
}

func (q *Queries) GetSettlement(ctx context.Context, arg GetSettlementParams) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, getSettlement, arg.PayerID, arg.PayeeID)
	var i Settlement
	err := row.Scan(&i.PayerID, &i.PayeeID, &i.Amount)
	return i, err
}

const listSettlements = `-- name: ListSettlements :many
SELECT payer_id, payee_id, amount
FROM settlements, (SELECT id FROM members WHERE group_id = $1) AS members
WHERE payer_id = members.id OR payee_id = members.id
`

func (q *Queries) ListSettlements(ctx context.Context, groupID int32) ([]Settlement, error) {
	rows, err := q.db.QueryContext(ctx, listSettlements, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Settlement{}
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(&i.PayerID, &i.PayeeID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlement = `-- name: UpdateSettlement :one
UPDATE settlements
SET amount = $3
WHERE payer_id = $1 AND payee_id = $2
RETURNING payer_id, payee_id, amount
`

type UpdateSettlementParams struct {
	PayerID int32  `json:"payer_id"`
	PayeeID int32  `json:"payee_id"`
	Amount  string `json:"amount"`
}

func (q *Queries) UpdateSettlement(ctx context.Context, arg UpdateSettlementParams) (Settlement, error) {
	row := q.db.QueryRowContext(ctx, updateSettlement, arg.PayerID, arg.PayeeID, arg.Amount)
	var i Settlement
	err := row.Scan(&i.PayerID, &i.PayeeID, &i.Amount)
	return i, err
}
