// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupInvitation(ctx context.Context, arg CreateGroupInvitationParams) (GroupInvitation, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpense(ctx context.Context, id int32) error
	DeleteGroup(ctx context.Context, id int32) error
	DeleteGroupInvitation(ctx context.Context, code string) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteSettlement(ctx context.Context, arg DeleteSettlementParams) error
	DeleteUser(ctx context.Context, id string) error
	GetExpense(ctx context.Context, id int32) (GetExpenseRow, error)
	GetGroup(ctx context.Context, id int32) (Group, error)
	GetGroupInvitation(ctx context.Context, code string) (GroupInvitation, error)
	GetLineGroup(ctx context.Context, lineID sql.NullString) (Group, error)
	GetMember(ctx context.Context, id int32) (Member, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Member, error)
	GetSettlement(ctx context.Context, arg GetSettlementParams) (Settlement, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListExpenses(ctx context.Context, groupID int32) ([]ListExpensesRow, error)
	ListExpensesWithinDate(ctx context.Context, arg ListExpensesWithinDateParams) ([]ListExpensesWithinDateRow, error)
	ListGroups(ctx context.Context, userID string) ([]ListGroupsRow, error)
	ListMembersOfGroup(ctx context.Context, groupID int32) ([]ListMembersOfGroupRow, error)
	ListNonSettledExpenses(ctx context.Context, groupID int32) ([]ListNonSettledExpensesRow, error)
	ListSettlements(ctx context.Context, groupID int32) ([]Settlement, error)
	SummarizeExpensesWithinDate(ctx context.Context, arg SummarizeExpensesWithinDateParams) ([]SummarizeExpensesWithinDateRow, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateSettlement(ctx context.Context, arg UpdateSettlementParams) (Settlement, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
